version: '3.3'
services:
  backend:
    image: 592115001/234project-backend:latest
    ports: 
      - "8084:8080"
  frontend:
    image: dto80/project234-frontend:latest
    ports:
      - "8083:80"
    volumes:
      - type: bind
        source: setting.json
        target: /usr/share/nginx/html/assets